### ISSUE TITLE
Add new events on eg.Flicking

### ISSUE THREAD

**Issue by incleaf** [naver/egjs#215]
## Description

I've used another carousel library which supports `beforeInit` and `afterInit` event. Can you add these events on `eg.Flicking`? I think these are commonly used events for web component libraries.

**Comment by sculove** [comment]
@incleaf Thank you for your advice.
We will talk about this issue.
Could you tell me another carousel Plz.?

**Comment by incleaf** [comment]
I'm currently using OwlCarousel 1.x

**Comment by netil** [comment]
Sorry to be late on commenting.

We talked about this issue, but we decided to not add new `initialization` related custom events, because eg.Flicking is executed synchronously, so if you need some point to catch that moment, you can do without any custom event as below.

```js

// <-- beforeInit: run some code at this point
var flicking = new eg.Flicking();
// <-- afterInit: run some code at this point

```

Anyway, thanks for your comment and interest.
Any further comments and suggestion will be appreciated.

**Comment by incleaf** [comment]
Thank you for your kind comment. Your presentation on DEVIEW was really good 😄  I'll keep interest on egjs.
