### ISSUE TITLE
Check Disqus

### ISSUE THREAD

**Issue by mixed** [naver/egjs#223]

**Comment by jongmoon** [comment]
This issue is that disqus is not appeared in bottom of documentation(http://naver.github.io/egjs/latest/doc/) 

![image](https://cloud.githubusercontent.com/assets/3255471/15494899/ed4e3afe-21c7-11e6-8309-0f425f3484b2.png)


The reason for this is that disqus info is not provided.

egjs uses egjs-jsdoc-template(https://github.com/naver/egjs-jsdoc-template) as a document automation tool. And egjs refers it on package.json.

```js
 "devDependencies": {
    "browserstack-runner": "^0.4.1",
    "egjs-jsdoc-template": "*",
    "grunt": "^0.4.5",
```

But egjs-jsdoc-template does not have default setting for disqus in conf.json(https://github.com/naver/egjs-jsdoc-template/blob/master/conf.json).

```js
"templates": {
		"disqus": "",
```

So we should update that information before documentation is built.

**Comment by jongmoon** [comment]
Ignore above reason. 

> egjs refers settings in EGJS-ROOT/jsdoc.json not the setting in egjs-jsdoc-template.

Real reason is as below.

> egjs domain is not set up in disqus. 

I've just created it (egjs.disqus.com). and I'll work like below.

![image](https://cloud.githubusercontent.com/assets/3255471/15671529/48e562f4-2766-11e6-9f5d-f619f09bff52.png)
