### ISSUE TITLE
check to work on jQuery3.0, Hammer.js 2.0.8

### ISSUE THREAD

**Issue by mixed** [naver/egjs#362]

**Comment by jongmoon** [comment]
I've just checked unit test on Safari/FireFox/Chrome on MAC OSX.

**Unit Test Failed Count**

|              | Chrome 53 | Safari | FireFox |
|--------------|-----------|--------|---------|
| class        | 0         | 0      | 0       |
| component    | 0         | 0      | 0       |
| cssPrefix    | 12        | 12     | 12      |
| eg           | 0         | 0      | 0       |
| flicking     | 1         | 1      | 0       |
| infiniteGrid | 0         | 0      | 0       |
| module       | 0         | 0      | 0       |
| movableCoord | 0         | 0      | 0       |
| pauseResume  | 0         | 0      | 0       |
| persist      | 0         | 0      | 0       |
| rotate       | 0         | 0      | 0       |
| scrollEnd    | 0         | 0      | 0       |
| transform    | 1         | 1      | 1       |
| visible      | 0         | 0      | 0       |

**Comment by jongmoon** [comment]
The [transform issue](#385) is caused by jQuery ~3.1 bug and jQuery foundation has plan to fix this next release(3.2). 

I think it would be better not to fix it.

**Comment by netil** [comment]
In case of eg.Flicking error, occurs because of comparison of element's style existence.
I found something weird on attribute setting on jQuery 3.0, but I'm not really sure that is jQuery's problem.

It behaves not removing attribute itself.
Normally, executing below code it removes.

```js
// expected behavior is removing 'style' attribute
$("#some").attr("style", null);
```

But, in the code example that I made, after creating MovableCoord instance, it doesn't remove attribute, just removes its value only.

- https://output.jsbin.com/kegebi/

I'm suspicious on Hammer.js's code, but to solve this issue, I'll try to change comparison condition.

**Comment by netil** [comment]
Bear in mind, that jQuery `slim` version excludes below functionalities, which effects (ex. timing function $.easing) used by egjs, make difficult to use slim version.

> ## Slim Build
> All in all, it excludes ajax, effects, and currently deprecated code.
> https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/
