### ISSUE TITLE
flicking has wrong position on disableInput mode

### ISSUE THREAD

**Issue by sculove** [naver/egjs#433]
## Description
flicking should set position when resizing.

## Steps to check or reproduce
1. call disableInput method.
2. rotate window
3. call resize method.

**Comment by netil** [comment]
## Why this occurs
disable/enable are implemented via changing event bindings.
- https://github.com/naver/egjs/blob/master/src/flicking.js#L1506

When `.disableInput()` is called, all of MovableCoords's event binds are unbinded
and `.resize()` adjust panel's position using MovableCoords's method, which can't not handle because all event binds are gone.
- https://github.com/naver/egjs/blob/master/src/flicking.js#L1440

## Todo
Modify `.disableInput()` and `.enableInput()` in other way rather than handling with event binds.

**Comment by netil** [comment]
The only and easiest way to do without handling event biding, is calling MovableCoord's `._setInterrupt()` method.

But, internally after changes(animation or coord moves) happens, it changes calling `this._setInterrupt(false);`

- In case of no duration:
https://github.com/naver/egjs/blob/master/src/movableCoord.js#L779

- on animationEnd:
https://github.com/naver/egjs/blob/master/src/movableCoord.js#L602

Is kind of duplicated call, but to be worked as expected, it needed to call `._setInterrupt()` regardless MovableCoord's call.

**Comment by netil** [comment]
It's not good idea approaching via private method.
It'll be better implement disableInput/enableInput API in MovableCoord component

**Comment by sculove** [comment]
@netil I agree it. I will handle it in MovableCoord. Thanks
