### ISSUE TITLE
flicking in flicking

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs#490]
### ko
이전 jindo에서는 FLICKING 안에 FLICKING 요소가 있을때 이벤트를 내려주지 않아 플리킹 안에 플리킹이 안정적으로 이루여졌습니다.
이번 EGJS도 마찬가지긴 하지만 플리킹을 빨리 할때 안의 요소가 플리킹 중이거나 할때 다시 플리킹 액션을 취하면 겉의 FLICKING 이 움직이는 현상이 있는데요 이를 해결하고자 이벤트를 안내려주는 방법등을 써보곤 있는데 잘 해결이 되질 않습니다.
혹시 관련하여 해결하신 분이나 해결 방법을 아시는 분 계실까요?

### en
Previously jindo did not drop an event when there was a FLICKING element in FLICKING, so flicking was stable in Flicking. This EGJS is also the same, but if the element is flicking when you are flicking fast or if you take the flicking action again, the FLICKING moves out. I have been trying to solve this problem by sending an event, but I can not solve it well.

Do you know someone who has solved the problem or how to solve it?

**Comment by mixed** [comment]
@changdongchun 
Thank you for your issue. We will reply to you soon. :)

**Comment by netil** [comment]
@changdongchun could you provide some online demo for that? (like jsbin, jsfiddle, etc.)

**Comment by changdongchun** [comment]
https://jsfiddle.net/changDongChun/pftv58vx/1/

**Comment by netil** [comment]
@changdongchun I'm not able to read full of your code, just roughly checking, your structure is like
having main flicking and a child flicking within.

```html
<div id="cateMainFlick">
	...
	<div id="mbnflick_017001" class="mbnFlickArea">
```
	
```js
var mbnF_017001 = new eg.Flicking("#mbnflick_017001", { ... });

var cateMainFlick = new eg.Flicking("#cateMainFlick", , { ... });
```

And what you need is when doing some flick action on child flicking, you're having
issue on parent flicking.

Since 1.5.0, there's new method to [disable](http://naver.github.io/egjs/latest/doc/eg.Flicking.html#disableInput) and enable input. You can try using these APIs.
When you're dealing with child, disable the parent from custom event.

For ex.

```js
var mbnF_017001 = new eg.Flicking("#mbnflick_017001", {
	flick : function(e) {
		cateMainFlick.disableInput();
	},
	flickEnd : function(e) {
		...
		cateMainFlick.enableInput();
	},
	restore : function(e) {
		...
		cateMainFlick.enableInput();
	}
});
```

**Comment by changdongchun** [comment]
Perfect resolved that the problem was resolved
